---
image: $CI_REGISTRY/docker-images/infratools:latest

stages:
- build

build_image:
  timeout: 2 hours
  stage: build
  script:
  - packer init  ./Packer/windows-guitest-runner.pkr.hcl
  - packer build ./Packer/windows-guitest-runner.pkr.hcl
  tags:
  - linux-docker