---
# yamllint disable rule:line-length
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
  - block:
    - name: Populate instance config
      set_fact:
        instance_conf: "{{ lookup('file', molecule_instance_config) | from_yaml }}"
        skip_instances: false
    rescue:
    - name: Populate instance config when file missing
      set_fact:
        instance_conf: {}
        skip_instances: true

  - name: Destroy molecule instance(s)
    ec2:
      state: absent
      region: "{{ item.region }}"
      instance_ids: "{{ item.instance_id }}"
    register: server
    with_items: "{{ instance_conf }}"
    when: not skip_instances
    async: 7200
    poll: 0
    notify:
    - Dump instance config

  - name: Wait for instance(s) deletion to complete
    async_status:
      jid: "{{ item.ansible_job_id }}"
    register: ec2_jobs
    until: ec2_jobs.finished
    retries: 300
    with_items: "{{ server.results }}"

  # Mandatory configuration for Molecule to function.

  - name: Populate instance config
    set_fact:
      instance_conf: {}

  handlers:
  - name: Dump instance config
    copy:
      content: |
        # Molecule managed
        {{ instance_conf | to_json | from_json | to_yaml }}
      dest: "{{ molecule_instance_config }}"
      mode: 0600
